language: haskell

sudo: false

##############################################################################
# Installing the `kpsewhich` program

# This program is required by the LaTeX/HTML test-suite.

# TODO (21 October 2015). The texlive-binaries package is only
# required by the LaTeX/HTML test-suite, so we should install this
# package only when TEST=non-require-stdlib.

addons:
  apt:
    packages:
    - texlive-binaries

##################################################################

# We build with all the latest GHC versions for each 7.X, so we reduce
# build times, possibly avoid compiler bugs and still test all the major
# interface changes.

ghc:
  - 7.8.4
  - 7.6.3

# We use the word 'test' in a broad sense (e.g. it includes the Agda
# test suite, the benchmark suite, the compilation with a specific set
# of dependencies, the testing of other programs like `hTags`, etc.) Almost
# all the tests are divided according to whether or not require the standard
# library.
#
# The current tests non-requiring the standard library are:
#
# make check-whitespace
# make succeed
# make fail
# make interaction
# make interactive
# make latex-html-test
# make examples
# make api-test
# make tests
# make TAGS (testing the hTags program)
#
# The current tests requiring the standard library are:
#
# make library-test
# make lib-succeed
# make lib-interaction
# make compiler-test
# make benchmark-without-logs
#
# Other tests: These tests use a some how different set up.
#
# ghc-7.8.4-transformers-0.3.0.0
# cpp

# Travis runs the builds on this order.
env:
  - TEST=non-require-stdlib
  - TEST=require-stdlib
  - TEST=ghc-7.8.4-transformers-0.3.0.0
  - TEST=cpp

install:
  # Asking for the shell.
  - echo $SHELL

  # The GHC version.
  - GHC_VERSION_TRAVIS=`ghc --numeric-version`

##############################################################################
# Installing latest versions of cabal-install, Alex and Happy

  - if [ $TEST = "non-require-stdlib" -o $TEST = "require-stdlib" ]; then
       cabal install cabal-install &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex &&
       cabal install happy;
    fi

##############################################################################
# Installing dependencies

# We use the `--avoid-reinstalls` flag with GHC 7.6.3/7.8.4 for
# avoiding to break previously installed packages [Issue 1520].

# Note: `cabal install` doesn't set up the number of jobs by default
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

  - case $TEST in
      "non-require-stdlib" | "require-stdlib")
        if [ $GHC_VERSION_TRAVIS = 7.6.3 -o $GHC_VERSION_TRAVIS = 7.8.4 ]; then
           cabal install --enable-tests --avoid-reinstalls --only-dependencies;
        else
           cabal install --enable-tests --only-dependencies;
        fi
        ;;
    esac

##############################################################################
# Installing Agda

# We are installing Agda using
#
#  cabal configure <options>
#  cabal build
#  cabal copy
#  cabal register
#
# instead of
#
#  cabal install <options>
#
# due to the cabal-install issue https://github.com/haskell/cabal/issues/975.

##############################################################################
# Running `cabal configure`

  - export BUILD_DIR=$PWD/dist

  - case $TEST in
      "non-require-stdlib" | "require-stdlib")
        cabal configure -v2 --builddir=$BUILD_DIR --enable-tests
        ;;
    esac

##############################################################################
# Running `cabal build`, `cabal copy` and `cabal register`

# Note: `cabal build` sets up the number of jobs to $ncpus by default.
# (cabal-install 1.22.4.0). See https://github.com/haskell/cabal/issues/2628.

# We don't run `cabal install` because we are using `cabal configure` and
# `cabal build` (see Section 'cabal install ≠ Setup install' from
# http://www.vex.net/~trebla/haskell/cabal-cabal.xhtml).

  - case $TEST in
      "non-require-stdlib" | "require-stdlib")
        travis_wait cabal build -v2 --builddir=$BUILD_DIR &&
        cabal copy &&
        cabal register
        ;;
    esac

##############################################################################
# Installing Epic

# The Epic backend has been removed. See Issue 1481.

  # - sudo apt-get install libgc-dev
  # - cabal install epic

##############################################################################
# Getting the standard library

  - if [ $TEST = "require-stdlib" ]; then
       make up-to-date-std-lib;
    fi

##############################################################################
# Testing compilation with transformers 0.3.0.0 which is shipped with
# GHC 7.8.* [Issues 1156 and 1539]

# N.B. that this test is not include in the Makefile tests.

# We use the `--avoid-reinstalls` flag with GHC 7.8.4 for avoiding to
# break previously installed packages [Issue 1520].

  - if [ $TEST = "ghc-7.8.4-transformers-0.3.0.0" -a $GHC_VERSION_TRAVIS = 7.8.4 ]; then
       cabal install cabal-install --constraint=transformers==0.3.0.0 &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex --constraint=transformers==0.3.0.0 &&
       cabal install happy --constraint=transformers==0.3.0.0 &&
       cabal install --enable-tests --avoid-reinstalls --only-dependencies --constraint=transformers==0.3.0.0 &&
       cabal configure -v2 --builddir=$BUILD_DIR --enable-tests --constraint=transformers==0.3.0.0 &&
       travis_wait cabal build -v2 --builddir=$BUILD_DIR;
    fi

##############################################################################
# Testing compilation with cpp instead of cpphs [Issue 1647]

# N.B. We will run this test only with the higher GHC version
# available in Travis.

# N.B. that this test is not include in the Makefile tests.

# We use the `--avoid-reinstalls` flag with GHC 7.8.4 for avoiding to
# break previously installed packages [Issue 1520].

  - if [ $TEST = "cpp" -a $GHC_VERSION_TRAVIS = 7.8.4 ]; then
       cabal install cabal-install &&
       export PATH=$HOME/.cabal/bin:$PATH &&
       cat $HOME/.cabal/config &&
       cabal install alex &&
       cabal install happy &&
       cabal install --enable-tests --avoid-reinstalls --only-dependencies &&
       cabal configure -v2 --enable-tests --builddir=$BUILD_DIR -f -cpphs &&
       travis_wait cabal build -v2 --builddir=$BUILD_DIR;
    fi

##############################################################################
# Installing fix-agda-whitespace

  - if [ $TEST = "non-require-stdlib" ]; then
       make install-fix-agda-whitespace;
    fi

##############################################################################

script:
# Right now Haddock doesn't work, presumably because it consumes too
# much memory.
  # - cabal haddock

##############################################################################

# We don't run LaTeX/XeLaTeX/LuaLaTeX on Travis (see Issues 1022 and
# 1675), but we still compare the generated tex/html files with the
# golden files.

  - if [ $TEST = "non-require-stdlib" ]; then
       make check-whitespace &&
       make BUILD_DIR=$BUILD_DIR succeed &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR fail &&
       make BUILD_DIR=$BUILD_DIR interaction &&
       make BUILD_DIR=$BUILD_DIR interactive &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR DONT_RUN_LATEX="Y" latex-html-test &&
       make BUILD_DIR=$BUILD_DIR examples &&
       make BUILD_DIR=$BUILD_DIR api-test &&
       make BUILD_DIR=$BUILD_DIR tests &&
       make BUILD_DIR=$BUILD_DIR TAGS;
    fi

##############################################################################

  - if [ $TEST = "require-stdlib" ]; then
       make BUILD_DIR=$BUILD_DIR library-test &&
       make BUILD_DIR=$BUILD_DIR lib-succeed &&
       make BUILD_DIR=$BUILD_DIR lib-interaction &&
       make AGDA_TESTS_OPTIONS="" BUILD_DIR=$BUILD_DIR compiler-test &&
       make BUILD_DIR=$BUILD_DIR benchmark-without-logs;
    fi

##############################################################################
matrix:
  exclude:
    - ghc: 7.6.3
      env: TEST=ghc-7.8.4-transformers-0.3.0.0
    - ghc: 7.6.3
      env: TEST=cpp

  # Builds are loooong, we want to send an email as fast as possible.
  fast_finish: true
  # allow_failures:
    # - ghc: A.B.C

##############################################################################
# Every master and maintenance branches >= 2.4.3 or >= maint-2.4.2 must
# be here. You can also add your private branches if you want travis to
# test them.

branches:
  only:
    - master
    - maint-2.4.2
    - travis-test
